os: [linux, osx] # ostrost/ostent flagged multi-os
language: c # Go runtime is managed with gvm
sudo: false
addons:
  apt:
    packages:
    - gcc-multilib
env:
  global:
    # RC- prefix til travis-dpl is unable to deploy into github PRE-release
    - ARTIF="RC-`uname -sm | tr ' ' .`"
    - GVMINSTALLER_URL=https://github.com/moovweb/gvm/raw/master/binscripts/gvm-installer
    - DPL_GO=go1.5 # Deploy only when this matches GVM_GO in the matrix.
  matrix:
  # - GVM_GO=tip
    - GVM_GO=go1.5
install:
  - set -e # errors are fatal
  - |
    if test x$TRAVIS_OS_NAME \!= xlinux ; then
      # linux is ok with gcc
      export CXX=clang++ CC=clang
      # default CC=gcc for `language: c'
    fi
  - if type -t gvm; then gvm get; else curl -sSL $GVMINSTALLER_URL | bash; fi
  - |
    if test x$TRAVIS_OS_NAME == xosx -a xx$GVM_GO == xxgo1.5 ; then
      GO_BINARY_PATH=~/.gvm/archive///////$GVM_GO.darwin-amd64-osx10.8.tar.gz
      GO_BINARY_URL=https://golang.org/dl/$GVM_GO.darwin-amd64.tar.gz
      test -f $GO_BINARY_PATH ||
      curl --silent --show-error --fail --location --output $GO_BINARY_PATH $GO_BINARY_URL
    fi
  - source ~/.gvm/scripts/gvm
  - gvm version
  - gvm install $GVM_GO --binary # || gvm install $GVM_GO
  - gvm use $GVM_GO; gvm list
  - cd; mkdir -p gopath/src; mv build gopath/src/github.com; cd gopath/src/github.com/$TRAVIS_REPO_SLUG
  - export GOPATH=~/gopath:$GOPATH PATH=~/gopath/bin:$PATH
  - go version; go env
  - make init
script: make --always-make test all # like make -B
before_deploy:
  - |
    if test x$GVM_GO \!= x$DPL_GO ; then
      x64=.non-dpl-go-to-be-removed
    fi
    if test x$TRAVIS_OS_NAME \!= xosx ; then # 32bit build on non-osx
      x32=.32
      make boot32 all32
    mv $HOME/gopath/bin/ostent.32  $HOME/gopath/bin/$ARTIF.32
    fi
  - mv $HOME/gopath/bin/ostent     $HOME/gopath/bin/$ARTIF$x64
  - set +e # off fatal errors for travis-dpl
after_deploy:
  - set -e # errors are fatal again
  - |
    if test x$TRAVIS_OS_NAME \!= xosx ; then # 32bit build on non-osx
    mv $HOME/gopath/bin/$ARTIF.32  $HOME/gopath/bin/ostent.32
    fi
  - mv $HOME/gopath/bin/$ARTIF$x64 $HOME/gopath/bin/ostent
deploy:
  file:
    - $HOME/gopath/bin/$ARTIF$x32
    - $HOME/gopath/bin/$ARTIF$x64
  skip_clean: true
  on:
    tags: true
    prerelease: true
    # condition may not work with prerelease:
    condition: $GVM_GO = $DPL_GO
  provider: releases # https://github.com/travis-ci/dpl#github-releases
  api_key:
    secure: >
      EFMPpR2rZkCdlfWuz7bE4ji3/0OL+fgIq+lXJ5SWDUG7aYWVqlLpR1hYXb0yqy8YA2Rg3xvAfPY/sFZvCyUMv0Wx1ZhiVzNvAUduzYFqovvHoYS4nuv0bXWis4YBnx7zJ7uikl5aGAOB8g0L+ofsUAswlDU5M9g9stDG4upWSgw=
