os: [linux, osx] # ostrost/ostent flagged multi-os
language: c # Go runtime is managed with gvm
sudo: false
env:
  global:
    - DPL_GO=go1.5.3 # Deploy only when this matches GVM_GO in the matrix.
  matrix:
    - GVM_GO=go1.5.3
  # - GVM_GO=tip
install:
  - source ./tools/ci/step.sh install.1
  - source ./tools/ci/step.sh install.2 $GVM_GO $TRAVIS_OS_NAME
  - source ./tools/ci/step.sh install.3 $GVM_GO
  - source ./tools/ci/step.sh install.4 $GVM_GO $TRAVIS_REPO_SLUG
  - source ./tools/ci/step.sh Gmake init
script:
  - source ./tools/ci/step.sh Gmake --always-make test all
before_deploy:
  - source ./tools/ci/step.sh before_deploy.1 $TRAVIS_OS_NAME
  - source ./tools/ci/step.sh before_deploy.2 $TRAVIS_OS_NAME
  - source ./tools/ci/step.sh before_deploy.3 $TRAVIS_OS_NAME
deploy:
  file_glob: true
  file: $HOME/gopath/deploy/*
  on: {tags: true, condition: $GVM_GO = $DPL_GO}
  provider: releases
  prerelease: true
  api_key:
    secure: >
      EFMPpR2rZkCdlfWuz7bE4ji3/0OL+fgIq+lXJ5SWDUG7aYWVqlLpR1hYXb0yqy8YA2Rg3xvAfPY/sFZvCyUMv0Wx1ZhiVzNvAUduzYFqovvHoYS4nuv0bXWis4YBnx7zJ7uikl5aGAOB8g0L+ofsUAswlDU5M9g9stDG4upWSgw=
