os: [linux, osx] # ostrost/ostent flagged multi-os
language: c # Go runtime is managed with gvm
sudo: false
env:
  global:
    - DPL_GO=go1.5.3 # Deploy only when this matches GVM_GO in the matrix.
  matrix:
    - GVM_GO=go1.5.3
  # - GVM_GO=tip
install:
  - source ./tools/ci/step.sh install1st
  - source ./tools/ci/step.sh install2nd $GVM_GO $TRAVIS_OS_NAME
  - source ./tools/ci/step.sh install3rd $GVM_GO
  - source ./tools/ci/step.sh install4th $GVM_GO $TRAVIS_REPO_SLUG
  - source ./tools/ci/step.sh Gmake init
script:
  - source ./tools/ci/step.sh Gmake --always-make test all
before_deploy:
  - source ./tools/ci/step.sh before-deploy1st $TRAVIS_OS_NAME
  - source ./tools/ci/step.sh before-deploy2nd $TRAVIS_OS_NAME
  - source ./tools/ci/step.sh before-deploy3rd $TRAVIS_OS_NAME
deploy:
  skip_clean: true
  file_glob: true
  file: [$HOME/gopath/src/github.com/$TRAVIS_REPO_SLUG/*]
  on: {tags: true, condition: $GVM_GO = $DPL_GO}
  provider: releases
  prerelease: true
  api_key:
    secure: >
      EFMPpR2rZkCdlfWuz7bE4ji3/0OL+fgIq+lXJ5SWDUG7aYWVqlLpR1hYXb0yqy8YA2Rg3xvAfPY/sFZvCyUMv0Wx1ZhiVzNvAUduzYFqovvHoYS4nuv0bXWis4YBnx7zJ7uikl5aGAOB8g0L+ofsUAswlDU5M9g9stDG4upWSgw=
