os: [linux, osx] # ostrost/ostent flagged multi-os
language: c # Go runtime is managed with gvm
sudo: false
env:
  matrix:
  # - GVM_GO=tip
    - GVM_GO=go1.5.3
  global:
    - DPL_DIR=~/deploy # ~/deploy is outside the clone dir
    - DPL_GO=go1.5.3 # Deploy only when this matches GVM_GO in the matrix.
install:
  - source ./tools/ci/step.sh install_1
  - source ./tools/ci/step.sh install_2 $GVM_GO $TRAVIS_OS_NAME
  - source ./tools/ci/step.sh install_3 $GVM_GO
  - source ./tools/ci/step.sh install_4 $GVM_GO $TRAVIS_REPO_SLUG
  - source ./tools/ci/step.sh Gmake init
script:
  - source ./tools/ci/step.sh Gmake --always-make test all
before_deploy:
  - source ./tools/ci/step.sh before_deploy_1 $TRAVIS_OS_NAME
  - source ./tools/ci/step.sh before_deploy_2 $TRAVIS_OS_NAME
  - source ./tools/ci/step.sh before_deploy_3
  - source ./tools/ci/step.sh before_deploy_4
  - source ./tools/ci/step.sh prior_to_deploy # must be last one
deploy:
  file_glob: true
  file: $HOME/deploy/*
  on: {tags: true, condition: $GVM_GO = $DPL_GO}
  provider: releases
  prerelease: true
  api_key:
    secure: >
      EFMPpR2rZkCdlfWuz7bE4ji3/0OL+fgIq+lXJ5SWDUG7aYWVqlLpR1hYXb0yqy8YA2Rg3xvAfPY/sFZvCyUMv0Wx1ZhiVzNvAUduzYFqovvHoYS4nuv0bXWis4YBnx7zJ7uikl5aGAOB8g0L+ofsUAswlDU5M9g9stDG4upWSgw=
